/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.lms;

public class App {

    public static void main(String[] args) {
      int num = 1;
      String title = "자바 프로젝트 실습";
    
        System.out.printf("번호 : %d%n", num);
        System.out.printf("수업명 : %s%n", title);
        System.out.println("설명 : 자바 프로젝트를 통한 자바 언어 활용법 익히기");
        System.out.println("시작일 : 2019-01-02");
        System.out.println("종료일 : 2019-05-28");
        System.out.println("총 수업시간 : 1000 시간");
        System.out.println("일 수업시간 : 8 시간");
        
        System.out.println("번호 : " + 1); //문자열 리터럴과 숫자 리터럴 합치기
        System.out.println("수업명 : 자바 프로젝트 실습"); //문자열 리터럴 출력
    }
}
