/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.lms;
import java.util.Scanner;

public class App2 {
    
    public static void main(String[] args) {
     Scanner scanner = new Scanner(System.in);
     System.out.println("암호를 입력하세요");
     int num = scanner.nextInt();
     
        System.out.println("번호 : 1");
        System.out.println("이름 : 홍길동");
        System.out.println("이메일 : hong@test.com");
        System.out.println("암호 : " + num);
        System.out.println("사진 : hong.png");
        System.out.println("전화 : 1111-2222");
        System.out.println("가입일 : 2019-01-01");
    }
}
