/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.lms;
import java.util.*;
import java.sql.Date;


public class App {

  public static void main(String[] args) {

    int i = 0;
    final int a = 50;
    Lesson[] l1 = new Lesson[a];

    Scanner sc = new Scanner(System.in);

    while(i < a) {
      Lesson l2 = new Lesson();

      System.out.print("번호? ");
      l2.num = Integer.parseInt(sc.nextLine());

      System.out.print("수업명? ");
      l2.title = sc.nextLine();

      System.out.print("수업내용? ");
      l2.study = sc.nextLine();

      System.out.print("시작일? ");
      l2.start_date = Date.valueOf(sc.nextLine());

      System.out.print("종료일? ");
      l2.end_date = Date.valueOf(sc.nextLine());

      System.out.print("총수업시간? ");
      l2.full_time = sc.nextLine();

      System.out.print("일수업시간? ");
      l2.day_time = sc.nextLine();
      l1[i] = l2;

      i++;

      System.out.println();
      System.out.print("계속 입력하시겠습니까?(Y/n) ");
      String str = sc.nextLine();

      if (str.equalsIgnoreCase("y") || str.equals("")) {
        System.out.println();
        continue;
      } if(!str.equalsIgnoreCase("y") && !str.equals("")) {
        break;
      }

    }
    sc.close();
    System.out.println();

    int j;
    for(j = 0; j < i; j++) {
      System.out.printf("%d, %-15s, %s ~ %s, %10s\n", 
          l1[j].num, l1[j].title, l1[j].start_date, l1[j].end_date, l1[j].full_time);
    }

  }
}
