/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.lms;
import java.util.*;
import java.sql.Date;
public class App {

  static final int LENGTH = 50;
  static Scanner sc = new Scanner(System.in);

  static Lesson[] l1 = new Lesson[LENGTH];
  static Board[] b1 = new Board[LENGTH];
  static Member[] m1 = new Member[LENGTH];

  static int l_size = 0;
  static int m_size = 0;
  static int b_size = 0;


  static String cmd() {

    System.out.print("명령> ");
    return sc.nextLine();
  }

  static void addLesson() {

    Lesson l2 = new Lesson();

    System.out.print("번호? ");
    l2.num = Integer.parseInt(sc.nextLine());

    System.out.print("수업명? ");
    l2.title = sc.nextLine();

    System.out.print("수업내용? ");
    l2.study = sc.nextLine();

    System.out.print("시작일? ");
    l2.start_date = Date.valueOf(sc.nextLine());

    System.out.print("종료일? ");
    l2.end_date = Date.valueOf(sc.nextLine());

    System.out.print("총수업시간? ");
    l2.full_time = sc.nextLine();

    System.out.print("일수업시간? ");
    l2.day_time = sc.nextLine();

    l1[l_size] = l2;

    l_size++;

    System.out.println("저장하였습니다.");

  }

  static void addMember() {

    Member m2 = new Member();

    System.out.print("번호? ");
    m2.num = Integer.parseInt(sc.nextLine());

    System.out.print("이름? ");
    m2.name = sc.nextLine();

    System.out.print("이메일? ");
    m2.email = sc.nextLine();

    System.out.print("암호? ");
    m2.pwd = sc.nextLine();

    System.out.print("사진? ");
    m2.phone = sc.nextLine();

    System.out.print("전화? ");
    m2.phone = sc.nextLine();

    m2.today = new Date(System.currentTimeMillis());

    m1[m_size] = m2;

    m_size++;

    System.out.println("저장하였습니다.");

  }

  static void addBoard() {

    Board b2 = new Board();

    System.out.print("번호 ? ");
    b2.num = Integer.parseInt(sc.nextLine());

    System.out.print("내용 ? ");
    b2.contents = sc.nextLine();   

    b2.view = 5;

    b2.today = new Date(System.currentTimeMillis());

    b1[b_size] = b2;

    b_size++;

    System.out.println("저장하였습니다.");

  }

  static void listLesson() {

    for(int j = 0; j < l_size; j++) {
      System.out.printf("%d, %-15s, %s, %s ~ %s, %-5s\n", 
          l1[j].num, l1[j].title, l1[j].study, l1[j].start_date, l1[j].end_date, l1[j].day_time);
    }

  }

  static void listMember() {

    for(int j = 0; j < m_size; j++) {
      System.out.printf("%d, %s, %s, %s %5$tY-%5$tm-%5$td\n", 
          m1[j].num, m1[j].name, m1[j].email, m1[j].phone, m1[j].today);
    }

  }

  static void listBoard() {

    for(int j = 0; j < b_size; j++) {
      System.out.printf("%d, %s, %3$tY-%3$tm-%3$td, %4$d\n", 
          b1[j].num, b1[j].contents, b1[j].today, b1[j].view);
    }

  }

  public static void main(String[] args) {


    while(true) {
      
      String keyboard = cmd();
      
      if (keyboard.equals("/lesson/add")) {

        addLesson();

      } else if (keyboard.equals("/member/add")) {

        addMember();

      } else if (keyboard.equals("/board/add")) {

        addBoard();

      } else if (keyboard.equals("/lesson/list")){ 

        listLesson();

      } else if (keyboard.equals("/member/list")) {

        listMember();

      } else if (keyboard.equals("/board/list")) {

        listBoard();

      } else if(keyboard.equals("quit")) {
        System.out.println("안녕!");
        break;
      }  else {
        System.out.println("실행할 수 없는 명령어입니다.");
      }
    } sc.close();
  }
}
