/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.lms;
import java.util.*;
public class App {

  public static void main(String[] args) {

    Scanner sc = new Scanner(System.in);

    System.out.print("번호? ");
    int num = sc.nextInt();

    sc.nextLine();

    System.out.print("수업명? ");
    String title = sc.nextLine();

    System.out.print("수업내용? ");
    String study = sc.nextLine();

    System.out.print("시작일? ");
    String start_date = sc.nextLine();

    System.out.print("종료일? ");
    String end_date = sc.nextLine();

    System.out.print("총수업시간? ");
    String full_time = sc.nextLine();

    System.out.print("일수업시간? ");
    String day_time = sc.nextLine();



    System.out.printf("번호 : %d\n", num);
    System.out.printf("수업명 : %s\n", title);
    System.out.printf("수업내용 : %s\n", study);
    System.out.printf("시작일 : %s\n", start_date);
    System.out.printf("종료일 : %s\n", end_date);
    System.out.printf("총수업시간 : %s\n", full_time);
    System.out.printf("일수업시간 : %s\n", day_time);


  }
}
