/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.lms;
import java.util.Scanner;
import java.sql.Date;

public class App2 {
  
  public static void main(String[] args) {
    
    int i = 0;
    final int j = 50;
    Member[] m1 = new Member[j];

    Scanner sc = new Scanner(System.in);
    
    while(i < j) {

      Member m2 = new Member();
      
      System.out.print("번호? ");
      m2.num = Integer.parseInt(sc.nextLine());

      System.out.print("이름? ");
      m2.name = sc.nextLine();

      System.out.print("이메일? ");
      m2.email = sc.nextLine();

      System.out.print("암호? ");
      String pwd = sc.nextLine();

      System.out.print("사진? ");
      String photo = sc.nextLine();

      System.out.print("전화? ");
      m2.phone = sc.nextLine();

      System.out.print("가입일? ");
      m2.today = Date.valueOf(sc.nextLine());
      
      m1[i] = m2;

      i++;

      System.out.println();
      System.out.print("계속 입력하시겠습니까?(Y/n) ");
      String str = sc.nextLine();

      if (str.equalsIgnoreCase("y") || str.equals("")) {

        continue;
      } if (!str.equalsIgnoreCase("y") && !str.equals("")) {
        break;
      }

    }
    sc.close();
    System.out.println();
    
    int a;
    for(a = 0; a < i; a++) {
      System.out.printf("%d, %4s, %-10s, %-12s, %s\n",
          m1[a].num, m1[a].name, m1[a].email, m1[a].phone, m1[a].today);
    }

  }

}
