/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.lms;
import java.sql.Date;
import java.util.Scanner;

public class App3 {

  public static void main(String[] args) {

    int[] num = new int[100];
    String[] a = new String[100];
    Date[] today = new Date[100];
    int[] view = new int[100];

    Scanner sc = new Scanner(System.in);
    int i = 0;

    okok:
      while(true) {

      System.out.print("번호 ? ");
      num[i] = sc.nextInt();

      sc.nextLine();

      System.out.print("내용 ? ");
      a[i] = sc.nextLine();   

      view[i] = 0;

      System.out.print("계속 하시겠습니까?(Y/n)");
      String str = sc.nextLine();

      today[i] = new Date(System.currentTimeMillis());

      ++i;

      if(str.equalsIgnoreCase("y") ||str.equalsIgnoreCase("")) {
        continue;
      }
      if (!str.equalsIgnoreCase("y") || !str.equalsIgnoreCase("")) {
        break okok;  
      }
    }

    int j;
    for(j = 0 ; j < i ; j++ ) {
      System.out.printf("%d, %s, %s, %d\n", num[j], a[j], today[j], view[j]);
    }
    
  }
}
