/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.lms;
import java.util.Scanner;

public class App3 {

  public static void main(String[] args) {

    Scanner sc = new Scanner(System.in);

    System.out.print("번호 ? ");
    int num = sc.nextInt();
    
    sc.nextLine();
    
    System.out.print("내용 ? ");
    String a = sc.nextLine();
    
    System.out.print("작성일 ? ");
    String write = sc.nextLine();
    
    System.out.print("조회수 ? ");
    String view = sc.nextLine();
    int view1 = Integer.parseInt(view);
    
    System.out.printf("번호 : %d\n내용 : %s\n작성일 : %s\n조회수 : %d\n", 
        num, a, write, view1);

  }
}
