/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.lms;
import java.util.Date;
import java.util.Scanner;

public class App3 {

  public static void main(String[] args) {

    Scanner sc = new Scanner(System.in);
    Date w_today = new Date();
    int view = 5;

    System.out.print("번호 ? ");
    int num = sc.nextInt();
    
    sc.nextLine();
    
    System.out.print("내용 ? ");
    String a = sc.nextLine();   

    System.out.printf("번호 : %d\n내용 : %s\n", num, a);
    System.out.printf("작성일 : %1$tY-%1$tm-%1$td\n", w_today);
    System.out.printf("조회수 : %d\n", view);

  }
}
